name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build packages and images
    runs-on: ubuntu-latest
    container:
      image: alpine:3.20.3
    env:
      SIGNING_KEY: git@shibe.nl-67292f84
      ABUILD_WORKING_DIRECTORY: ${{ github.workspace }}/apk
      ALPINE_RELEASE_VERSION: 3.20.2
      ALPINE_APORTS_VERSION: 3.20-stable
      OPENFORTIVM_VPN_VERSION: 1.22.1_git20241106
      OPENFORTIVM_CONF_VERSION: 3.18.1_git20241106
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment
        env:
          SIGNING_KEY_RSA: ${{ secrets.ABUILD_RSA_KEY }}
          SIGNING_KEY_RSA_PUB: ${{ vars.ABUILD_RSA_KEY_PUB }}
        run: |
          chmod +x scripts/prepare-env.sh
          scripts/prepare-env.sh ${ABUILD_WORKING_DIRECTORY}
          
      - name: Build APK packages
        run: |
          doas -u build sh ${ABUILD_WORKING_DIRECTORY}/build-packages.sh ${ABUILD_WORKING_DIRECTORY} ${SIGNING_KEY} ${ALPINE_APORTS_VERSION} ${OPENFORTIVM_VPN_VERSION} ${OPENFORTIVM_CONF_VERSION}

      - name: Build ISO images
        run: |
          doas -u build sh ${ABUILD_WORKING_DIRECTORY}/build-images.sh ${ABUILD_WORKING_DIRECTORY} ${ALPINE_RELEASE_VERSION}

      - name: Prepare workflow artifacts
        if: (!startsWith(github.ref, 'refs/tags/'))
        run: |
          chmod +x scripts/prepare-upload.sh
          scripts/prepare-upload.sh ${GITHUB_WORKSPACE} ${ABUILD_WORKING_DIRECTORY} git$(date +"%Y%m%d")+${GITHUB_SHA:0:7}

      - name: Upload workflow artifacts
        if: (!startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v4
        with:
          name: openfortivm-build-artifacts-${{ github.run_number }}
          path: ${{ github.workspace }}/publish

      - name: Prepare release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          chmod +x scripts/prepare-upload.sh
          scripts/prepare-upload.sh ${GITHUB_WORKSPACE} ${ABUILD_WORKING_DIRECTORY} ${GITHUB_REF_NAME}

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            publish/iso/*
            publish/apk/*
